# Generated by Django 6.0 on 2025-12-24 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assets",
            fields=[
                ("asset_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("Brand", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("working_status", models.CharField(max_length=50)),
                ("memory", models.CharField(max_length=100)),
                ("operating_system", models.CharField(max_length=100)),
                ("vendor", models.CharField(max_length=100)),
                ("warranty_start", models.DateField()),
                ("warranty_end", models.DateField()),
                ("span", models.IntegerField()),
                ("current_status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField()),
                ("employee_name", models.CharField(max_length=100)),
                ("employee_email", models.CharField(max_length=255)),
                ("employee_location", models.CharField(max_length=100)),
                (
                    "employee_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RETURNED", "Returned")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("joining_date", models.DateField()),
                ("exit_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.CharField(max_length=8)),
                (
                    "sr_type",
                    models.CharField(
                        choices=[
                            ("NEW_JOINEE", "New Joiner"),
                            ("REPLACEMENT_ASSET", "Replacement"),
                            ("EXIT", "exit"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "current_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_sr",
                        to="assets.assets",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to="assets.employee",
                    ),
                ),
                (
                    "replacement_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_sr",
                        to="assets.assets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="allocations",
            fields=[
                (
                    "allocation_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("allocated_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RETURNED", "Returned")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="assets.assets",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="assets.employee",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="assets.servicerequest",
                    ),
                ),
            ],
        ),
    ]
